[project]
name = "taker-links"
version = "0.1.0"
description = ""
authors = [{ name = "Niktia Parfenov", email = "n.a.parfenov@edu.mtuci.ru" }]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "dotenv (>=0.9.9,<0.10.0)",
    "loguru (>=0.7.3,<0.8.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
aiosqlite = "^0.21.0"
asyncio = "^3.4.3"
aiohttp = {extras = ["speedups"], version = "^3.12.14"}
flet = "^0.28.3"

[tool.poetry.group.extras.dependencies]
black = "^25.1.0"
mypy = "^1.17.0"
